---Romika Chaudhary---
---C0921918---
---S06 C11P Character Functions---
---Nov 7, 2023---

--1
SELECT DEALER_NAME AS "Dealer", UPPER(DEALER_STREET || ' ' || DEALER_CITY || ', ' || DEALER_STATE || ' ' || DEALER_ZIP) AS "Address"
FROM p_dealers
WHERE DEALER_ID IN(101, 407, 120)
ORDER BY "Dealer";

--2
SELECT LOWER(LAST_NAME || ', ' || FIRST_NAME) AS "Previous Owner", LOWER(OWNER_STREET || ' ' || OWNER_CITY || ', ' || OWNER_STATE || ' ' || OWNER_ZIP) AS "Address"
FROM p_previous_owners
WHERE OWNER_ID BETWEEN 1010 AND 1015
ORDER BY "Previous Owner";

--3
SELECT CONCAT('Previous Owner : ', UPPER(LAST_NAME)) AS "Previous Owners"
FROM p_previous_owners
WHERE OWNER_STATE = 'MI' AND OWNER_CITY = 'Ann Arbor'
ORDER BY LAST_NAME;

--4
SELECT DISTINCT UPPER(OWNER_CITY) AS "CITY", LENGTH(OWNER_CITY) AS "CITY_LENGTH"
FROM p_previous_owners
ORDER BY "CITY";

--5
SELECT DEALER_NAME, MANAGER_ID
FROM p_dealers
WHERE MANAGER_ID IS NOT NULL
ORDER BY DEALER_NAME;

--6
SELECT DEALER_NAME, MANAGER_ID
FROM p_dealers
WHERE MANAGER_ID IS NULL
ORDER BY DEALER_NAME;

--7
SELECT DEALER_NAME, MANAGER_ID
FROM p_dealers
WHERE MANAGER_ID IS NOT NULL
ORDER BY DEALER_NAME;

--8
SELECT MODEL_YEAR || ' ' || CAR_MAKE || ' ' || CAR_MODEL AS "Cars with no previous owner"
FROM p_cars
WHERE PREVIOUS_OWNER_ID IS NULL
ORDER BY MODEL_YEAR;


--9
SELECT (SUBSTR(FIRST_NAME, 1, 1) || ', ' || LAST_NAME) AS NAME
FROM p_previous_owners
WHERE LOWER(OWNER_CITY) = LOWER(:ENTER_CITY)
ORDER BY LAST_NAME DESC;

--10
SELECT FIRST_NAME || ' ' || LAST_NAME AS "PREVIOUS_OWNER", INITCAP(OWNER_CITY) AS "CITY"
FROM p_previous_owners
WHERE LOWER(OWNER_CITY) LIKE 'b%'
ORDER BY "PREVIOUS_OWNER";

--11
SELECT MODEL_YEAR, CAR_MAKE, CAR_MODEL, CONCAT('$', SELLING_PRICE)
FROM p_cars
WHERE CAR_MAKE IN ('Dodge', 'Nissan', 'Lincoln') AND
SELLING_PRICE BETWEEN 71000 AND 74000
ORDER BY MODEL_YEAR,
CAR_MAKE,
CAR_MODEL,
SELLING_PRICE DESC;

--12
SELECT FIRST_NAME || ' ' || LAST_NAME AS "NAME"
FROM p_previous_owners
WHERE LOWER(FIRST_NAME || '' || LAST_NAME) LIKE LOWER('%at%') 
ORDER BY LAST_NAME;

