--Romika Chaudhary--
--C0921918--
--S09 Group Functions--
--Nov 17, 2023--

--ANSWER 1

SELECT TO_CHAR(AVG(PRICE), '999.99') AS "AVERAGE_PRICE" 
FROM B_PRICES
WHERE END_DATE IS NOT NULL;


--ANSWER 2

SELECT TO_CHAR(SUM(QUANTITY*PRICE_PAID), '$99,999.99') AS "TOTAL_ORDERS" 
FROM B_ORDER_LINES;


--ANSWER 3

SELECT TO_CHAR(MIN(MONTHLY_SALARY), '9999.99') AS "LOW_SALARY", TO_CHAR(MAX(MONTHLY_SALARY), '99999.99') AS "HIGH_SALARY", TRUNC(AVG(MONTHLY_SALARY), 2) AS "AVG_SALARY",
TO_CHAR(MAX(HIRE_DATE), 'MM/DD/YYYY') AS "LAST_HIRE_DATE", MIN(LAST_NAME) AS "LOW_NAME", MAX(LAST_NAME) AS "HIGH_NAME"
FROM B_EMPLOYEES;


--ANSWER 4

--ONE(1)


--ANSWER 5

SELECT DISTINCT COUNT(PRODUCT_CODE) AS "Number of Products", TO_CHAR(TRUNC(AVG(PRICE), 2), '$9,999.99') AS "Average Price"
FROM B_PRODUCTS
WHERE CATEGORY_CODE = 'LA';


--ANSWER 6

SELECT COUNT(ORDER_ID) AS "Number of Orders" 
FROM B_ORDERS 
WHERE EXTRACT(YEAR FROM ORDER_DATE) = 2020;


--Answer 7

SELECT COUNT(CUSTOMER_ID) AS "Count", TO_CHAR(TRUNC(AVG(CREDIT_LIMIT), 2), '99,999.99') AS "Avg Cr Limit", TO_CHAR(TRUNC(AVG(BALANCE), 2), '99,999.99') AS "Avg Balance",
TO_CHAR(SUM(CREDIT_LIMIT - BALANCE), '999,999.99') AS "Total Cr Avail", TO_CHAR(TRUNC(AVG(CREDIT_LIMIT - BALANCE), 2), '99,999.99') AS "Avg Cr Avail"
FROM B_CUSTOMERS;


--Answer 8

SELECT COUNT(DISTINCT CUST_CITY) AS "CITIES" 
FROM B_CUSTOMERS;


--Answer 9

SELECT COUNT(*) AS "Customers with no Discount"
FROM B_CUSTOMERS
WHERE DISCOUNT IS NULL;





