-- Romika Chaudhary --
-- C0921918 --
-- S10 ORDER BY --
-- NOV 20, 2023 --

--10
SELECT CUST_STATE, CUSTOMER_NAME, COALESCE(TO_CHAR(DISCOUNT, '0.999'), '0.005') AS "Discount"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CO', 'NY', 'SC')
ORDER BY CUST_STATE, DISCOUNT;


--11
SELECT CUST_STATE, CUSTOMER_NAME, COALESCE(TO_CHAR(DISCOUNT, '0.999'), 'Not assigned') AS "Discount"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CA', 'NV', 'TX')
ORDER BY CUST_STATE, CUSTOMER_NAME;


--12
SELECT TO_CHAR(ORDER_DATE, 'Month, DD, YYYY') AS "Order date", ORDER_ID AS "Order ID", CUSTOMER_ID AS "Customer", COALESCE(TO_CHAR(SHIP_DATE, 'Month, DD, YYYY'), 'Not shipped') AS "Ship date"
FROM B_ORDERS
ORDER BY ORDER_DATE, ORDER_ID;


--GROUP_BY
--1
SELECT CATEGORY_CODE, TO_CHAR(ROUND(AVG(PRICE), 2), '$9,999.99') AS "Average price"
FROM B_PRODUCTS
GROUP BY CATEGORY_CODE
HAVING AVG(price) > 1500.00
ORDER BY CATEGORY_CODE;


--2
SELECT CUST_STATE AS "State", COUNT(CUSTOMER_ID) AS "Customer Count", TO_CHAR(ROUND(AVG(BALANCE), 2), '$99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CA', 'MI', 'SC', 'TX')
GROUP BY CUST_STATE
ORDER BY CUST_STATE;


--3
SELECT CUST_STATE AS "State", CUST_CITY AS "City", COUNT(CUSTOMER_ID) AS "Customer Count", AVG(BALANCE) AS "Average Balance"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CO', 'NV')
GROUP BY CUST_CITY, CUST_STATE
ORDER BY CUST_STATE, CUST_CITY;


--4
SELECT EXTRACT(YEAR FROM MEMBERSHIP_DATE) AS "Year", EXTRACT(MONTH FROM MEMBERSHIP_DATE) AS "Month", COUNT(CUSTOMER_ID) AS "Customer ID"
FROM B_CUSTOMERS
GROUP BY MEMBERSHIP_DATE
ORDER BY MEMBERSHIP_DATE;


--5
SELECT CUST_STATE AS "State", INITCAP(CUST_CITY) AS "City", COUNT(CUSTOMER_ID) AS "Customer Count", TO_CHAR(TRUNC(AVG(BALANCE), 2), '$99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
GROUP BY CUST_STATE, INITCAP(CUST_CITY)
HAVING COUNT(CUSTOMER_ID) > 1 
ORDER BY "State", "City";


--6
SELECT CUST_STATE AS "State", INITCAP(CUST_CITY) AS "City", COUNT(CUSTOMER_ID) AS "Customer Count", TO_CHAR(TRUNC(AVG(BALANCE), 2), '$99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CA', 'CO', 'NV')
GROUP BY CUST_STATE, INITCAP(CUST_CITY)
HAVING AVG(BALANCE) BETWEEN 22000 AND 60000 
ORDER BY "State", "City";





