-- Romika Chaudhary --
-- C0921918 --
-- S15 Multiple Subqueries --
-- December 1, 2023 --

--1
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "EMPLOYEE", JOB_TITLE, MONTHLY_SALARY
FROM B_EMPLOYEES
JOIN B_DEPARTMENTS USING (DEPARTMENT_CODE)
JOIN B_JOBS USING (JOB_CODE)
WHERE JOB_TITLE IN (SELECT JOB_TITLE FROM B_EMPLOYEES WHERE JOB_TITLE IN ('Department Manager', 'Software Developer'))
ORDER BY DEPARTMENT_NAME, 
    LAST_NAME;


--2
SELECT FIRST_NAME, LAST_NAME, MONTHLY_SALARY AS "SALARY" 
FROM B_EMPLOYEES
WHERE MONTHLY_SALARY <= ALL (SELECT MONTHLY_SALARY FROM B_EMPLOYEES);


--3
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "EMPLOYEE", MONTHLY_SALARY
FROM B_EMPLOYEES
JOIN B_DEPARTMENTS USING (DEPARTMENT_CODE)
WHERE MONTHLY_SALARY = ANY (SELECT MIN(MONTHLY_SALARY) FROM B_EMPLOYEES
                                GROUP BY DEPARTMENT_CODE)
ORDER BY DEPARTMENT_NAME,
    LAST_NAME;


--4
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "EMPLOYEE", MONTHLY_SALARY
FROM B_EMPLOYEES
JOIN B_DEPARTMENTS ON B_EMPLOYEES.DEPARTMENT_CODE = B_DEPARTMENTS.DEPARTMENT_CODE
WHERE MONTHLY_SALARY >= ANY (SELECT MAX(MONTHLY_SALARY) FROM B_EMPLOYEES E WHERE E.DEPARTMENT_CODE = B_EMPLOYEES.DEPARTMENT_CODE)                          
ORDER BY DEPARTMENT_NAME;


--5
SELECT 
    CUSTOMER_NAME,
    ORDER_ID,
    SHIP_DATE - ORDER_DATE AS DAYS_TO_SHIP
FROM B_CUSTOMERS
JOIN B_ORDERS ON B_CUSTOMERS.CUSTOMER_ID = B_ORDERS.CUSTOMER_ID
WHERE SHIP_DATE - ORDER_DATE > ANY (SELECT AVG(SHIP_DATE - ORDER_DATE) FROM B_ORDERS O WHERE O.CUSTOMER_ID = B_ORDERS.CUSTOMER_ID)
ORDER BY DAYS_TO_SHIP DESC;      

